### ISSUE TITLE
Servers cannot provide compatibility with 1.x and legacy 0.x at the same time

### ISSUE THREAD

**Issue by em-** [dbnicholson/ostree-push#11]
At the moment if a server gets upgraded to 1.x all the 0.x clients stop to work since the protocol has changed but the name of server-side handler has remained the same, so there's no way to make 0.x and 1.x to coexist on the server.

To avoid having to coordinate a flag day, it would be nice to be able to have both handlers installed under versioned name, with a thin dispatcher to provide backward compatibility with clients not using the versioned handlers through some simple heuristics.

**Comment by dbnicholson** [comment]
This is in release 1.2.0 now.
