### ISSUE TITLE
AttributeError: 'OSTreePusher' object has no attribute 'remote_path'

### ISSUE THREAD

**Issue by pciavald** [dbnicholson/ostree-push#3]
Hi, there's a typo [here](https://github.com/dbnicholson/ostree-push/blob/master/ostree-push#L302), `remote_path` should be `remotepath`

**Comment by dbnicholson** [comment]
Thanks. I think this was also fixed in the ea2bd121bb9345ebeac519e8caa6e9d22433da20 rewrite.
