### ISSUE TITLE
ostree-push fails due to permission error

### ISSUE THREAD

**Issue by davisRoman** [dbnicholson/ostree-push#9]
ostree-push fails due to permission error. ostree-receive command appears to need escalated priveleges on the remote side. https://pastebin.com/bDT7a6mm

**Comment by dbnicholson** [comment]
The idea is that the repos are owned by the user you're connecting to SSH with. I.e., you create an `ostree` user, create the repos as that user, and attach an SSH authorized key to the user.

It appears that the repos are owned by `root` in your case. Is that right? If so, then I think the only way `ostree-receive` will work out of the box for you is if you allow SSH as `root`. `ostree-receive` doesn't attempt to change user or anything like that.

**Comment by davisRoman** [comment]
@dbnicholson, you hit the nail on the head!  This was a newbie mistake on my end. Thank you very much!
